name: Run Commands

on: [push]

jobs:
  commands:
    runs-on: ubuntu-latest

    steps:
      - name: Show message
        run: echo "Hello!"

      - name: Show directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Show OS
        run: uname -a
